#!/usr/bin/env python
# -*- coding: utf-8 -*-

import urllib.request
import re
from bs4 import BeautifulSoup

DOMAIN = 'http://scriptoj.mangojuice.top/'

def get_title(id):
    url = DOMAIN + 'problems/' + id
    ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3380.0 Safari/537.36'
    request = urllib.request.Request(url)
    request.add_header('User-Agent', ua)
    try:
        content = urllib.request.urlopen(request)
    except urllib.error.HTTPError as e:
        print('Problem {0} fetch error, errorCode: {1}'.format(str(id), e.getcode()))
        return None
    soup = BeautifulSoup(content, "html.parser", from_encoding='gb18030')
    title = soup.find_all('h3', {"class": "problem-title"})
    ret = re.sub(r"\s{2,}", " ", title[0].text)
    return ret

def main():
    arr = []
    for i in range(102, -1, -1):
        print(i)
        t = get_title(str(i))
        if t == None:
            continue
        url = DOMAIN + 'problems/' + str(i)
        filename = 'script-oj-' + str(i) + '.js'
        line = '| [{0}]({1}) | [{2}](./{3}) | 🌟 |\n'.format(t, url, filename, filename)
        arr.append(line)

    with open('./README.md', 'w') as f:
        f.write('## ScriptOJ 解答\n\n')
        f.write('> Generated by [crawler.py](./crawler.py).\n\n')
        f.write(DOMAIN + 'problems?tag=all\n\n')
        f.write('---\n\n')
        f.write('| id | sol | rate |\n')
        f.write('| :--- | :--- | :--- |\n')
        f.writelines(arr)
        f.write('\n\n> - EOF -')
    
    print('Done!')

if __name__ == '__main__':
    main()
